### ISSUE TITLE
Unexpected "public" at line 59

### ISSUE THREAD

**Issue by remotevase** [remotevase/HomeTP#1]

**Comment by applqpak** [comment]
HahaHahahahahahahahahahahahahhahahahaha.

**Comment by applqpak** [comment]
1. From what I see you're ending the switch statement with a closing curly bracket(}) and then using another case?

**Comment by applqpak** [comment]
You have a missing }

**Comment by remotevase** [comment]
Wait... How did you get that? I'm just ending the whole command part, and then getting onto the disable part! Speak remote_vase language please, as I did NOT understand that post XD

**Comment by remotevase** [comment]
Thanks, lemme check...

**Comment by applqpak** [comment]
Lol. You didn't close the public function onCommand()

**Comment by remotevase** [comment]
Now its unexpected default line 56. I think I can fix this!

**Comment by applqpak** [comment]
Lol, wrong symbol xD
