### ISSUE TITLE
Undefined Property WAT!

### ISSUE THREAD

**Issue by remotevase** [remotevase/HomeTP#2]
`Notice: Undefined property: pocketmine\command\PluginCommand::$getName in phar://C:/Users/********/IM-Testing/plugins/phar_HomeTP-Source_PFQD1lOGifs1wVz.phar/src/HomeTP/HomeTP.php on line 22`

**Comment by remotevase** [comment]
$getName isnt even written! IM can be so crazy sometimes

**Comment by applqpak** [comment]
..... Lol .....

**Comment by Taki21** [comment]
Lol U are forgetting a pair of these () after getName
like
getName()

They think u mean
$this->getName
like u use $this->config

**Comment by Taki21** [comment]
That Work???

**Comment by remotevase** [comment]
Lemme check soon. 3rd period now, can check 4th period.

**Comment by remotevase** [comment]
Oops, forgot. I need a mobile device in order to check XD I'll check afterschool
