### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by remotevase** [remotevase/HomeTP#5]
`critical> ClassNotFoundException: "Class HomeTP\Color not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
`

**Comment by Taki21** [comment]
lol u use C:: like me xD

**Comment by remotevase** [comment]
Yeah, much easier, although it sometimes gets a little confusing between COLOR and C

**Comment by Taki21** [comment]
xD

**Comment by dragonwocky** [comment]
There's a difference between Colour and C?

**Comment by remotevase** [comment]
You just gotta choose something!. Ya know this statement?

Use pocketmine/utils/textformat as [c or color or whatever]

**Comment by dragonwocky** [comment]
ya thats what i use
