### ISSUE TITLE
Homes.yml

### ISSUE THREAD

**Issue by remotevase** [remotevase/HomeTP#7]
Doesn't save to homes.yml. /sethome <name> generates a "homes.yml" file, but never saves anything to it. It's just empty.

**Comment by Taki21** [comment]
how does it look? like:

## ...

?

**Comment by dragonwocky** [comment]
We dk, just got this report from someone on the forums

**Comment by remotevase** [comment]
That's why I added this. It's not like I could test it...

**Comment by remotevase** [comment]
IDK how it looks...

**Comment by applqpak** [comment]
Lemme look.

**Comment by applqpak** [comment]
What is $homeData?

**Comment by remotevase** [comment]
$homeData is the config.

**Comment by remotevase** [comment]
No one? Not a single person after a whole dang month. #squad @thelucyclub @TheDragonRing @Taki21 @applqpak @ImagicalGamer who has most experience with configs? Certainly not me...

**Comment by remotevase** [comment]
Fixed after tons of other bugfixes before
