### ISSUE TITLE
Ops can run home command

### ISSUE THREAD

**Issue by remotevase** [remotevase/HomeTP#8]
Ops can run the /home and /sethome command. I added the player isop function, but it keeps giving me an error. Unexpected else line 34

**Comment by applqpak** [comment]
Lemme look.

**Comment by remotevase** [comment]
line 34 i said

**Comment by Taki21** [comment]
ok ill check in few days due to state test examinations ...

**Comment by remotevase** [comment]
Few days, you say? ITS BEEN OVER A MONTH!!!!!!

**Comment by remotevase** [comment]
Fixed after tons of other bugfixes before
